/*CREATE ROW TABLE EMPLOYEE(
	ID INT NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	ADDRESS VARCHAR(100),
	MOBILE_NUMBER INT
);*/
/*CREATE TYPE "FIRST"."JOINOUT" AS TABLE (
   EMPLOYEE_ID INTEGER,
   EMPLOYEE_NAME VARCHAR(25),
   MOBILE_NUMBER VARCHAR(10),
   GROSS_MONTHLY DECIMAL(7,2),
    BASIC_MONTHLY DECIMAL(7,2)
);*/
/*INSERT INTO "FIRST"."EMPLOYEE" values(599,'Manohar','Chennai','9484564848');*/
/*CREATE TABLE "FIRST"."SALARY_STRUCTURE"(
	ID INT primary key NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	GROSS_MONTHLY DECIMAL(7,2),
	BASIC_MONTHLY DECIMAL(7,2),
	HRA_MONTHLY DECIMAL(7,2),
	ALLOWANCES DECIMAL(7,2),
	PF DECIMAL(6,2)
);*/
/*SELECT * FROM "FIRST"."EMPLOYEE";*/
/*Alter table "FIRST"."EMPLOYEE" Add ("MOBILE_NUMBER" varchar(10));*/
/*Alter table "FIRST"."EMPLOYEE" Drop ("MOBILE_NUMBER");*/
/*update "FIRST"."EMPLOYEE" set MOBILE_NUMBER = '9484564848' WHERE ID=123;*/

/*INSERT INTO "FIRST"."SALARY_STRUCTURE" values(123,'Karthik Shetty',35000.00,20000,7000,5000,3000);*/
/*SELECT * FROM "FIRST"."SALARY_STRUCTURE";*/
/*GRANT SELECT ON SCHEMA FIRST TO _SYS_REPO WITH GRANT OPTION;*/
GRANT SYS_DATABASES TO SYSTEM; 
/*call "FIRST"."test::selectData"(599,?);*/
/*call "FIRST"."test::joinWithInput"(599,?);*/
/*ALTER TABLE "FIRST"."SALARY_STRUCTURE" COLUMN */